bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# fix scrolling
set -g mouse on

# Start from index 1
set -g base-index 1
setw -g pane-base-index 1

# Rebind from ctrl b to ctrl a
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Rebind from ctrl & to ctrl x
# split window
unbind &
bind x kill-window

# DESIGN TWEAKS
#### BASIC CLEAN LOOK ####

# no bells
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none

# status bar location
set -g status-position top

# left side: session + window
set -g status-left ""

# lengths
set -g status-left-length 40
set -g status-right-length 50

# Overall Colors
set -g status-style "bg=#000000 fg=#FFFFFF"

# Date (Right Side)
set -g status-right "#[fg=#FFFFFF]%Y-%m-%d"

# Inactive Window Colors
setw -g window-status-format "#[fg=#FFFFFF,bg=#000000] #I:#W "

# Active Window Colors
setw -g window-status-current-format "#[fg=#000000,bg=#FFFFFF] #I:#W "
